default_stages: [commit, push]

exclude: |
  ^\.venv/
  ^migrations/

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        # args: ["backend/"]
        include: \.py$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        # args: ["backend/"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        # args: ["backend/"]
        include: \.py$
