[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
exclude = ["migrations"]

[tool.ruff.lint]
extend-select = ["I", "N", "UP", "B"]  # I: isort, N: pep8-naming, UP: pyupgrade, B: bugbear
ignore = ["E501"]  # Ignore line-too-long since Black handles it

[tool.mypy]
python_version = 3.11
check_untyped_defs = true
ignore_missing_imports = true
