# API Tests

@base_url = http://localhost:8000

###
# Get Statuses
GET {{base_url}}/patients/today-status-board/
Content-Type: application/json
accept: application/json


# Login
###
POST {{base_url}}/auth/login/
Content-Type: application/json
accept: application/json 

{
  "email": "surgeon@hospital.com",
  "password": "password"
}

## Get Patient List
###
GET {{base_url}}/patients/
Content-Type: application/json
accept: application/json
Authorization: Bearer xxxx
